using System.ComponentModel.DataAnnotations;


namespace BarmanBank.ViewModels
{
    public class LoginViewModel
    {
        [Required] public required string Username { get; set; }
        [Required, DataType(DataType.Password)] public string Password { get; set; }
    }

    public class RegisterViewModel
    {
        [Required] public required string Username { get; set; }
        [Required, DataType(DataType.Password)] public string Password { get; set; }
    }

    /*public class DepositViewModel
    {
        [Required, Range(1, double.MaxValue)]
        public decimal Amount { get; set; }
        public string RazorpayOrderId { get; set; }
    }*/
    public class DepositViewModel
    {
        [Required]
        [Range(1, 200000, ErrorMessage = "Deposit amount must be between ₹1 and ₹200,000")]
        public decimal Amount { get; set; }

        // Generated by server, NOT user input
        public string? RazorpayOrderId { get; set; }
    }

    public class WithdrawViewModel
    {
        [Required, Range(1, double.MaxValue)]
        public decimal Amount { get; set; }
        public string? RazorpayOrderId { get; set; }
    }
}
